# Importação

In [8]:
import pandas as pd
import glob
import os

Importando arquivos de 21-23

In [9]:
pasta_datasets = "Pi_3\\datasets"
arquivos_21_23 = glob.glob(os.path.join(pasta_datasets, "*.csv"))
print("arquivos:",arquivos_21_23)
dfs_21_23 = []

arquivos: ['Pi_3\\datasets\\MICRODADOS_ENEM_2021.csv', 'Pi_3\\datasets\\MICRODADOS_ENEM_2022.csv', 'Pi_3\\datasets\\MICRODADOS_ENEM_2023.csv']

Importando arquivos de 24-25

In [10]:
pasta_notas = "PI_3\\datasets\\24-25\\notas"
pasta_participantes = "PI_3\\datasets\\24-25\\participantes"
arquivos_notas = glob.glob(os.path.join(pasta_notas, "*.csv"))
arquivos_participantes = glob.glob(os.path.join(pasta_participantes, "*.csv"))
print("arquivos:",arquivos_notas)
print("arquivos:",arquivos_participantes)
dfs_24_25 = []

arquivos: ['PI_3\\datasets\\24-25\\notas\\RESULTADOS_2024.csv', 'PI_3\\datasets\\24-25\\notas\\RESULTADOS_2025.csv']
arquivos: ['PI_3\\datasets\\24-25\\participantes\\PARTICIPANTES_2024.csv', 'PI_3\\datasets\\24-25\\participantes\\PARTICIPANTES_2025.csv']

Listas

In [19]:
municipios = [3548500, 3551108, 3541000]

colunas_notas = [
    "NU_SEQUENCIAL",
    "NU_NOTA_CN",
    "NU_NOTA_CH",
    "NU_NOTA_LC",
    "NU_NOTA_MT",
    "NU_NOTA_REDACAO"
]

colunas_participantes = [
    "NU_INSCRICAO",
    "NU_ANO",
    "TP_COR_RACA",
    "CO_MUNICIPIO_PROVA",
    "Q006",
    "Q007",
    "Q020",
    "Q021",
    "Q023"
]

colunas_21_23 = [
    "NU_INSCRICAO",
    "NU_ANO",
    "TP_COR_RACA",
    "CO_MUNICIPIO_PROVA",
    "NU_NOTA_CN",
    "NU_NOTA_CH",
    "NU_NOTA_LC",
    "NU_NOTA_MT",
    "NU_NOTA_REDACAO",
    "Q006",
    "Q007",
    "Q020",
    "Q021",
    "Q023"
]

# Filtrando arquivos de 21-23

In [13]:
for i in arquivos_21_23:
    print(f"\nLendo arquivo: {i}")
    
    df = pd.read_csv(i, sep=';', encoding="latin1", usecols=colunas_21_23)
    df = df[df["CO_MUNICIPIO_PROVA"].isin(municipios)]
    display(df)
    dfs_21_23.append(df)

Lendo arquivo: Pi_3\datasets\MICRODADOS_ENEM_2021.csv

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,Q007,Q020,Q021,Q023
182,210054388672,2021,1,3548500,468.7,631.9,585.9,660.9,940.0,B,A,A,A,A
254,210054261848,2021,1,3548500,547.9,631.9,542.4,525.7,600.0,E,A,B,B,B
614,210052172134,2021,3,3548500,367.2,536.0,544.7,578.7,500.0,E,A,A,A,A
617,210052410091,2021,1,3541000,NaN,NaN,NaN,NaN,NaN,D,A,A,A,A
1787,210052177057,2021,1,3548500,NaN,NaN,NaN,NaN,NaN,C,A,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3387990,210052968317,2021,3,3541000,NaN,NaN,NaN,NaN,NaN,C,A,A,A,A
3388323,210052362500,2021,3,3548500,NaN,NaN,NaN,NaN,NaN,B,A,A,A,A
3388453,210053501889,2021,1,3541000,522.1,540.2,558.9,607.7,440.0,D,A,A,B,A
3389170,210053507254,2021,1,3548500,NaN,NaN,NaN,NaN,NaN,E,A,A,A,A
3389277,210051461989,2021,1,3548500,NaN,NaN,NaN,NaN,NaN,B,A,A,A,A

Lendo arquivo: Pi_3\datasets\MICRODADOS_ENEM_2022.csv

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,Q007,Q020,Q021,Q023
47,210056971736,2022,1,3548500,518.1,553.2,549.8,542.5,540.0,B,A,A,A,A
156,210055989203,2022,3,3548500,478.1,513.3,575.2,581.4,660.0,C,A,A,A,A
580,210057869140,2022,2,3541000,NaN,NaN,NaN,NaN,NaN,A,A,A,A,A
956,210057099234,2022,2,3541000,NaN,NaN,NaN,NaN,NaN,C,A,A,A,A
1093,210055952856,2022,1,3541000,452.6,575.9,551.7,617.0,460.0,H,A,A,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3473700,210055994879,2022,0,3541000,NaN,NaN,NaN,NaN,NaN,F,A,A,A,A
3473905,210056681691,2022,1,3548500,NaN,NaN,NaN,NaN,NaN,D,A,A,A,A
3474009,210055952141,2022,1,3541000,382.0,505.1,475.2,537.6,560.0,D,A,A,A,A
3474290,210055870937,2022,3,3548500,473.3,577.4,502.2,624.7,520.0,E,A,A,A,A
3474761,210056683146,2022,1,3548500,533.0,569.2,568.4,640.5,660.0,E,A,A,A,A

Lendo arquivo: Pi_3\datasets\MICRODADOS_ENEM_2023.csv

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,Q007,Q020,Q021,Q023
955,210061348795,2023,3,3548500,497.5,496.1,554.2,419.6,780.0,C,A,A,B,A
1132,210059602770,2023,1,3548500,399.7,520.4,544.5,469.7,560.0,B,A,A,A,A
3112,210058995889,2023,3,3548500,NaN,NaN,NaN,NaN,NaN,E,A,B,B,A
3605,210060079335,2023,1,3548500,NaN,NaN,NaN,NaN,NaN,I,A,A,A,B
5228,210061275698,2023,3,3548500,534.2,581.9,553.6,576.8,640.0,D,A,A,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933363,210060166873,2023,1,3541000,547.8,606.6,603.8,530.8,540.0,I,A,A,A,A
3933370,210061900114,2023,3,3541000,NaN,NaN,NaN,NaN,NaN,G,A,A,A,A
3933495,210059130056,2023,1,3541000,602.4,570.7,580.3,717.6,660.0,I,A,B,A,A
3933501,210059127740,2023,2,3548500,550.4,421.0,522.4,369.9,0.0,D,A,B,A,A
3933599,210059783833,2023,1,3548500,NaN,NaN,NaN,NaN,NaN,F,A,A,B,B

# Juntando os arquivos de 21 a 23

In [14]:
dfs_21_23 = pd.concat(dfs_21_23, ignore_index=True)
dfs_21_23 = dfs_21_23.sort_values(by=['NU_ANO'])
display(dfs_21_23)

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,Q007,Q020,Q021,Q023
0,210054388672,2021,1,3548500,468.7,631.9,585.9,660.9,940.0,B,A,A,A,A
1,210054261848,2021,1,3548500,547.9,631.9,542.4,525.7,600.0,E,A,B,B,B
2,210052172134,2021,3,3548500,367.2,536.0,544.7,578.7,500.0,E,A,A,A,A
3,210052410091,2021,1,3541000,NaN,NaN,NaN,NaN,NaN,D,A,A,A,A
4,210052177057,2021,1,3548500,NaN,NaN,NaN,NaN,NaN,C,A,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28330,210060166873,2023,1,3541000,547.8,606.6,603.8,530.8,540.0,I,A,A,A,A
28331,210061900114,2023,3,3541000,NaN,NaN,NaN,NaN,NaN,G,A,A,A,A
28332,210059130056,2023,1,3541000,602.4,570.7,580.3,717.6,660.0,I,A,B,A,A
28333,210059127740,2023,2,3548500,550.4,421.0,522.4,369.9,0.0,D,A,B,A,A
28334,210059783833,2023,1,3548500,NaN,NaN,NaN,NaN,NaN,F,A,A,B,B

# Filtrando arquivos de 24 e 25

In [20]:
for n, p in zip(arquivos_notas, arquivos_participantes):
    print(f"\nLendo arquivos {n} e {p}")

    df_notas = pd.read_csv(n, sep=';', encoding="latin1", usecols=colunas_notas)
    df_participantes = pd.read_csv(p, sep=';', encoding="latin1", usecols=colunas_participantes)


    df_notas = df_notas.sort_values(by=["NU_SEQUENCIAL"]).reset_index(drop=True)
    df_participantes = df_participantes.sort_values(by=['NU_INSCRICAO']).reset_index(drop=True)

    df_junto = pd.concat([df_participantes, df_notas], axis=1)
    display(df_junto)
    dfs_24_25.append(df_junto)

Lendo arquivos PI_3\datasets\24-25\notas\RESULTADOS_2024.csv e PI_3\datasets\24-25\participantes\PARTICIPANTES_2024.csv

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,Q006,Q007,Q020,Q021,Q023,NU_SEQUENCIAL,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,210062064233,2024,1,4314902,B,C,B,B,A,1,NaN,NaN,NaN,NaN,NaN
1,210062064234,2024,1,4318903,B,E,B,A,A,2,485.7,429.5,470.8,431.1,580.0
2,210062064235,2024,1,4320107,B,J,B,A,A,3,NaN,NaN,NaN,NaN,NaN
3,210062064236,2024,3,4313409,A,C,B,A,A,4,NaN,NaN,NaN,NaN,NaN
4,210062064237,2024,1,4309209,A,A,B,A,A,5,514.0,555.2,533.0,415.4,520.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4332939,210066495575,2024,1,4314407,A,C,B,A,A,4332940,596.1,596.7,587.6,492.0,860.0
4332940,210066495576,2024,3,4314407,B,C,B,A,A,4332941,724.4,728.3,621.4,841.0,900.0
4332941,210066495577,2024,2,3518800,A,E,B,B,A,4332942,529.5,548.2,511.9,493.3,720.0
4332942,210066495578,2024,3,2930105,A,B,A,A,A,4332943,582.9,570.6,570.9,706.0,760.0
4332943,210066495579,2024,1,3555406,A,F,B,A,D,4332944,628.6,595.0,663.2,641.6,600.0

Lendo arquivos PI_3\datasets\24-25\notas\RESULTADOS_2025.csv e PI_3\datasets\24-25\participantes\PARTICIPANTES_2025.csv

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,Q006,Q007,Q020,Q021,Q023,NU_SEQUENCIAL,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,210066506229,2025,2,2932200,B,B,A,A,A,1,NaN,NaN,NaN,NaN,NaN
1,210066506230,2025,1,2910800,A,D,B,B,A,2,429.1,538.6,547.9,632.3,640.0
2,210066506231,2025,1,3549805,A,F,B,C,C,3,470.2,388.0,554.9,435.8,460.0
3,210066506232,2025,3,2203909,A,B,B,B,D,4,556.3,437.4,449.5,408.0,540.0
4,210066506233,2025,1,5101803,B,Q,B,D,D,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4810767,210071444509,2025,1,2611606,B,I,B,D,D,4810768,NaN,NaN,NaN,NaN,NaN
4810768,210071444513,2025,1,3522208,A,C,B,B,E,4810769,NaN,NaN,NaN,NaN,NaN
4810769,210071444514,2025,1,3505708,B,I,B,B,A,4810770,593.2,626.5,611.5,824.0,620.0
4810770,210071444515,2025,2,3509502,B,C,B,B,A,4810771,NaN,NaN,NaN,NaN,NaN
4810771,210071444516,2025,3,3168606,B,C,B,B,A,4810772,610.5,545.0,588.4,744.3,800.0

# Juntando os arquivos 24 e 25

In [21]:
dfs_24_25 = pd.concat(dfs_24_25, ignore_index=True)
dfs_24_25 = dfs_24_25.drop(columns=["NU_SEQUENCIAL"])
dfs_24_25 = dfs_24_25[dfs_24_25["CO_MUNICIPIO_PROVA"].isin(municipios)]
display(dfs_24_25)

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,Q006,Q007,Q020,Q021,Q023,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
194,210062064599,2024,3,3548500,A,B,B,A,A,429.8,387.9,512.4,389.3,600.0
1446,210062066194,2024,1,3548500,B,D,B,B,A,377.1,464.4,529.1,537.4,580.0
1669,210062066572,2024,1,3548500,B,C,B,B,A,442.9,406.9,339.4,416.5,380.0
2302,210062067389,2024,1,3548500,B,H,B,C,E,NaN,NaN,NaN,NaN,NaN
2668,210062067755,2024,1,3541000,B,C,B,C,A,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9140200,210071439416,2025,1,3541000,A,C,B,A,A,NaN,NaN,NaN,NaN,NaN
9140926,210071440557,2025,1,3548500,A,C,B,A,A,522.4,411.0,389.1,349.6,0.0
9141798,210071441925,2025,3,3541000,B,C,B,A,A,495.7,498.1,530.7,537.3,460.0
9142984,210071443477,2025,3,3548500,B,H,B,B,E,567.0,544.1,477.0,524.6,500.0
9143202,210071443695,2025,2,3548500,A,C,B,B,A,NaN,NaN,NaN,NaN,NaN

# Juntando todos os arquivos de 21-25

In [22]:
df_final = pd.concat([dfs_21_23, dfs_24_25], ignore_index=True)
df_final = df_final.sort_values(by=['NU_ANO', 'CO_MUNICIPIO_PROVA'])
df_final.reset_index(drop=True)
display(df_final)

,NU_INSCRICAO,NU_ANO,TP_COR_RACA,CO_MUNICIPIO_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q006,Q007,Q020,Q021,Q023
3,210052410091,2021,1,3541000,NaN,NaN,NaN,NaN,NaN,D,A,A,A,A
5,210051202670,2021,2,3541000,457.7,423.9,411.1,494.4,620.0,E,A,A,A,A
6,210051681065,2021,3,3541000,561.6,648.2,562.2,484.6,660.0,G,A,A,B,B
10,210053955210,2021,1,3541000,NaN,467.7,556.9,NaN,500.0,C,A,A,A,A
12,210052472733,2021,3,3541000,NaN,NaN,NaN,NaN,NaN,A,A,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52706,210071438575,2025,1,3548500,NaN,NaN,NaN,NaN,NaN,A,H,B,B,A
52708,210071438912,2025,3,3548500,494.9,595.9,574.1,532.8,600.0,A,F,B,B,A
52713,210071440557,2025,1,3548500,522.4,411.0,389.1,349.6,0.0,A,C,B,A,A
52715,210071443477,2025,3,3548500,567.0,544.1,477.0,524.6,500.0,B,H,B,B,E
52716,210071443695,2025,2,3548500,NaN,NaN,NaN,NaN,NaN,A,C,B,B,A

In [ ]:
df_final.to_csv(os.path.join(pasta_datasets, "Dados_Enem_2021-2025.csv"), index=False, sep=';', decimal=',', encoding='latin1')